name: My first workflow

on: [push]
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
     
      - name: Create JS file
        run: echo "console.log('Hello, everyone!');" > hello.js
      - name: Run JS file
        run: node hello.js
